/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import CONTROL.ControlConcecionaria;
import MODELO.Cliente;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nestor
 */
public class ConsultaCliente extends javax.swing.JFrame {
    
    private final int NOMBRE = 0;
    private final int APELLIDO = 1;
    private final int DNI = 2;
    private final int DIRECCION = 3;
    private final int LOCALIDAD = 4;
    private final int TELEFONO = 5;
    private final int VEHICULO = 6;
    private DefaultTableModel modelo;
    private final ControlConcecionaria ctrl;
    
    public ConsultaCliente(ControlConcecionaria ctrl) {
        this.ctrl = ctrl;
        initComponents();
        modelar();
        for (int i = 0; i < ctrl.getCtrlConcecionaria().getTiene().size(); i++) {   
            for (int j = 0; j < ctrl.getCtrlConcecionaria().getTiene().get(i).getCompro().size(); j++) {                
                agregafilas(i,j);
            }
        }
    }

    private void modelar() {
        String data[][] = {};
        String col[] = {"NOMBRE", "APELLIDO", "DNI", "DIRECCION", "LOCALIDAD", "TELEFONO", "VEHICULO"};
        modelo = new DefaultTableModel(data, col);
        jTable1.setModel(modelo);
    }

    private void agregafilas(int i, int j) {
        modelo.insertRow(i, new Object[]{});
        modelo.setValueAt(verCliente(i).getNombre().toUpperCase(), i, NOMBRE);
        modelo.setValueAt(verCliente(i).getApellido().toUpperCase(), i, APELLIDO);
        modelo.setValueAt(verCliente(i).getDni(), i, DNI);
        modelo.setValueAt(verCliente(i).getDireccion().toUpperCase(), i, DIRECCION);
        modelo.setValueAt(verCliente(i).getLocalidad().toUpperCase(), i, LOCALIDAD);
        modelo.setValueAt(verCliente(i).getTelfijo(), i, TELEFONO);
        modelo.setValueAt(verCliente(i).getCompro().get(j).getCodigo(), i, VEHICULO);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setTitle("Resultados");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Buscar Codigo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        IngresoCodigo ic = new IngresoCodigo(ctrl);
        ic.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private Cliente verCliente(int i) {
        return(ctrl.getCtrlConcecionaria().getTiene().get(i));
    }
}
