/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import CONTROL.ControlConcecionaria;
import MODELO.Auto;
import MODELO.Camioneta;
import MODELO.Motocicleta;
import MODELO.Vehiculo;

/**
 *
 * @author Nestor
 */
public class ConsultaCodigo extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaCodigo
     */
    private final ControlConcecionaria ctrl;

    public ConsultaCodigo(int codigo, ControlConcecionaria ctrl) {
        initComponents();
        this.ctrl = ctrl;
        tipo.setText(irVehiculo(codigo).getEs().toUpperCase());
        estado.setText("Estado: " + irVehiculo(codigo).getEstado());
        marca.setText("Marca: " + irVehiculo(codigo).getMarca());
        modelo.setText("Modelo: " + irVehiculo(codigo).getModelo());
        patente.setText("Patente: " + irVehiculo(codigo).getPatente());
        anio.setText("Año: " + Integer.toString(irVehiculo(codigo).getAnio()));
        kilometraje.setText("Km: " + Integer.toString(irVehiculo(codigo).getKilometraje()));
        
        if ((irVehiculo(codigo).getEstado()).equals("Vendido")) {
            precio.setText("Precio: --");
            duenio.setText("Propietario: "+busquedaCliente(codigo).toUpperCase());
        } else {
            precio.setText("Precio:" + Integer.toString(irVehiculo(codigo).getPrecio()));
        }

        if (consultaEs(codigo).equals("automovil")) {
            op1.setText("Combustible: " + irAuto(codigo).getCombustible());
            op2.setText(gnc(codigo));
            op3.setText("Puertas: " + irAuto(codigo).getCantidadPuertas());
            op4.setText("Motor: " + Float.toString(irAuto(codigo).getCilmotor()));

        } else {
            if (consultaEs(codigo).equals("camioneta")) {
                op1.setText("Cabina: "+irCamioneta(codigo).getCabina());
                op2.setText("Traccion: "+traccion(codigo));
            } else {
                if (consultaEs(codigo).equals("motocicleta")) {
                    op1.setText("Cilindrada: "+irMoto(codigo).getCilindrada());
                }
            }
        }
    }

    private String consultaEs(int i) {
        return (ctrl.getCtrlConcecionaria().getVehiculo().get(i).getEs().toLowerCase());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        marca = new javax.swing.JLabel();
        anio = new javax.swing.JLabel();
        estado = new javax.swing.JLabel();
        modelo = new javax.swing.JLabel();
        kilometraje = new javax.swing.JLabel();
        precio = new javax.swing.JLabel();
        duenio = new javax.swing.JLabel();
        patente = new javax.swing.JLabel();
        op1 = new javax.swing.JLabel();
        op2 = new javax.swing.JLabel();
        op3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        op4 = new javax.swing.JLabel();
        tipo = new javax.swing.JLabel();

        setTitle("Resultados");

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(288, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(op3, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(op2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(op1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(marca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(anio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(estado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(patente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(modelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kilometraje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(precio, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(duenio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(op4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(modelo, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                    .addComponent(marca, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anio, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patente, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(duenio, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(op4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(op1, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(op2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(op3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ConsultaCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ConsultaCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ConsultaCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ConsultaCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ConsultaCodigo().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anio;
    private javax.swing.JLabel duenio;
    private javax.swing.JLabel estado;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel kilometraje;
    private javax.swing.JLabel marca;
    private javax.swing.JLabel modelo;
    private javax.swing.JLabel op1;
    private javax.swing.JLabel op2;
    private javax.swing.JLabel op3;
    private javax.swing.JLabel op4;
    private javax.swing.JLabel patente;
    private javax.swing.JLabel precio;
    private javax.swing.JLabel tipo;
    // End of variables declaration//GEN-END:variables

    private Vehiculo irVehiculo(int i) {
        return ((Vehiculo) ctrl.getCtrlConcecionaria().getVehiculo().get(i));
    }

    private Auto irAuto(int i) {
        return ((Auto) ctrl.getCtrlConcecionaria().getVehiculo().get(i));
    }

    private String busquedaCliente(int codigo) {
        String nombre = null;
        for (int i = 0; i < ctrl.getCtrlConcecionaria().getTiene().size(); i++) {
            for (int j = 0; j < ctrl.getCtrlConcecionaria().getTiene().get(i).getCompro().size(); j++) {
                if (codigo == Integer.parseInt(ctrl.getCtrlConcecionaria().getTiene().get(i).getCompro().get(j).getCodigo())) {
                    nombre = ctrl.getCtrlConcecionaria().getTiene().get(i).getApellido()+" "+ctrl.getCtrlConcecionaria().getTiene().get(i).getNombre();
                }
            }
        }
        return nombre;
    }

    private String gnc(int codigo) {
        if (irAuto(codigo).isGnc() == true) {
            return ("GNC");
        } else {
            return (null);
        }
    }

    private Camioneta irCamioneta(int i) {
        return ((Camioneta) ctrl.getCtrlConcecionaria().getVehiculo().get(i));
    }

    private String traccion(int codigo) {
        if (irCamioneta(codigo).isTraccion()) {
            return ("4x4");
        }else{
            return ("4x2");
        }
    }

    private Motocicleta irMoto(int i) {
        return ((Motocicleta) ctrl.getCtrlConcecionaria().getVehiculo().get(i));
    }
}
