/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import CONTROL.ControlConcecionaria;
import CONTROL.ControlIngresoClientes;
import Excepciones.AnioExcep;
import Excepciones.CamposNulosExcep;
import Excepciones.CodigoExcep;
import Excepciones.ConversionExcep;
import Excepciones.SinAutoExcep;
import Excepciones.SinClientesExcep;

import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Nestor
 */
public class RegistrarCliente extends javax.swing.JFrame {

    private final ControlConcecionaria ctrl;

    @SuppressWarnings({ "unchecked", "rawtypes" })
	public RegistrarCliente(ControlConcecionaria ctrl) throws SinAutoExcep {
        initComponents();
        this.ctrl = ctrl;
        ComboBoxVehiculo.setModel(new javax.swing.DefaultComboBoxModel(llenaComboBoxAutos(ctrl)));
        try {
            comboBoxCliente.setModel(new DefaultComboBoxModel(llenaComboBoxCliente(ctrl)));
        } catch (SinClientesExcep e) {
            existe.setEnabled(false);
            error.setText("AVISO: No tiene Clientes registrados, debe registrar un nuevo");
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({ "unchecked", "rawtypes" })
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        existe = new javax.swing.JRadioButton();
        nuevo = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        apellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dni = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        localidad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        cancelar = new javax.swing.JButton();
        aceptar = new javax.swing.JButton();
        comboBoxCliente = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        ComboBoxVehiculo = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        codigoBusqueda = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        error = new javax.swing.JLabel();

        setTitle("Registro Cliente");

        buttonGroup1.add(existe);
        existe.setText("Cliente Existente");
        existe.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                existeStateChanged(evt);
            }
        });

        buttonGroup1.add(nuevo);
        nuevo.setSelected(true);
        nuevo.setText("Nuevo Cliente");
        nuevo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                nuevoStateChanged(evt);
            }
        });

        jLabel1.setText("Nombre:");

        jLabel2.setText("Apellido:");

        jLabel3.setText("DNI:");

        jLabel4.setText("Direccion:");

        jLabel5.setText("Localidad:");

        jLabel6.setText("Telefono:");

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        comboBoxCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Clientes" }));
        comboBoxCliente.setEnabled(false);

        jLabel7.setText("Codigo Vehiculos Disponibles:");

        ComboBoxVehiculo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vehiculos" }));

        jLabel8.setText("Consulta:");

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nuevo)
                            .addComponent(existe)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jLabel4)
                                        .addGap(2, 2, 2)
                                        .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(comboBoxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel1)
                                                    .addComponent(jLabel3))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(dni, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(localidad, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(103, 103, 103))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboBoxVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codigoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscar)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(aceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelar)
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ComboBoxVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(codigoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar))
                .addGap(18, 18, 18)
                .addComponent(existe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboBoxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(localidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelar)
                    .addComponent(aceptar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(error, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void existeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_existeStateChanged
        if (existe.isSelected()) {
            comboBoxCliente.setEnabled(true);
        }
        if (!existe.isSelected()) {
            comboBoxCliente.setEnabled(false);
        }
    }//GEN-LAST:event_existeStateChanged

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void nuevoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_nuevoStateChanged
        if (nuevo.isSelected()) {
            jLabel1.setEnabled(true);
            jLabel2.setEnabled(true);
            jLabel3.setEnabled(true);
            jLabel4.setEnabled(true);
            jLabel5.setEnabled(true);
            jLabel6.setEnabled(true);
            direccion.setEnabled(true);
            dni.setEnabled(true);
            telefono.setEnabled(true);
            localidad.setEnabled(true);
            apellido.setEnabled(true);
            nombre.setEnabled(true);
        }
        if (!(nuevo.isSelected())) {
            jLabel1.setEnabled(false);
            jLabel2.setEnabled(false);
            jLabel3.setEnabled(false);
            jLabel4.setEnabled(false);
            jLabel5.setEnabled(false);
            jLabel6.setEnabled(false);
            direccion.setEnabled(false);
            dni.setEnabled(false);
            telefono.setEnabled(false);
            localidad.setEnabled(false);
            apellido.setEnabled(false);
            nombre.setEnabled(false);
        }
    }//GEN-LAST:event_nuevoStateChanged

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        ControlIngresoClientes c1 = new ControlIngresoClientes(ctrl);
        try {
            if (nuevo.isSelected()) {
                c1.setValues(apellido, dni, direccion, nombre, localidad, telefono, ComboBoxVehiculo);
            }
            if (existe.isSelected()) {
                c1.relaciona(ComboBoxVehiculo, comboBoxCliente);
            }
            this.dispose();
        } catch (ConversionExcep ex) {
            error.setText(ex.getMessage());
        } catch (AnioExcep ex) {
            error.setText(ex.getMessage());
        } catch (CamposNulosExcep ex) {
            error.setText(ex.getMessage());
        }
    }//GEN-LAST:event_aceptarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        try {
            CodigoExcep.validarCodigo(Integer.parseInt(codigoBusqueda.getText()), ctrl);
            ConsultaCodigo cc = new ConsultaCodigo(Integer.parseInt(codigoBusqueda.getText()), ctrl);
            cc.setVisible(true);
        } catch (NumberFormatException e) {
            error.setText("ERROR: Ingrese un codigo de busqueda valido");
        } catch (CodigoExcep ex) {
            error.setText(ex.getMessage());
        }
    }//GEN-LAST:event_buscarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboBoxVehiculo;
    private javax.swing.JButton aceptar;
    private javax.swing.JTextField apellido;
    private javax.swing.JButton buscar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField codigoBusqueda;
    private javax.swing.JComboBox comboBoxCliente;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField dni;
    private javax.swing.JLabel error;
    private javax.swing.JRadioButton existe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField localidad;
    private javax.swing.JTextField nombre;
    private javax.swing.JRadioButton nuevo;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables

    private String[] llenaComboBoxAutos(ControlConcecionaria ctrl) throws SinAutoExcep {
        int cont = 0;
        int cont2 = 0;
        String[] arrAux;
        for (int i = 0; i < ctrl.getCtrlConcecionaria().getVehiculo().size(); i++) {
            if (ctrl.getCtrlConcecionaria().getVehiculo().get(i).getEstado().equals("En Venta")) {
                cont++;
            }
        }
        if (cont != 0) {
            arrAux = new String[cont];
            for (int i = 0; i < ctrl.getCtrlConcecionaria().getVehiculo().size(); i++) {
                if (ctrl.getCtrlConcecionaria().getVehiculo().get(i).getEstado().equals("En Venta")) {
                    arrAux[cont2] = ctrl.getCtrlConcecionaria().getVehiculo().get(i).getCodigo();
                    cont2++;
                }
            }
            return (arrAux);
        } else {
            throw new SinAutoExcep();
        }
    }

    private String[] llenaComboBoxCliente(ControlConcecionaria ctrl) throws SinClientesExcep {
        if (ctrl.getCtrlConcecionaria().getTiene().isEmpty()) {
            throw new SinClientesExcep();
        }else{
        String[] arreNombre = new String[ctrl.getCtrlConcecionaria().getTiene().size()];

        for (int i = 0; i < ctrl.getCtrlConcecionaria().getTiene().size(); i++) {
            arreNombre[i] = ctrl.getCtrlConcecionaria().getTiene().get(i).getApellido() + " " + ctrl.getCtrlConcecionaria().getTiene().get(i).getNombre();
        }
        return (arreNombre);
        }
    }
}
